### ISSUE TITLE
remote:console not work on Rails 6

### ISSUE THREAD

**Issue by nPaul** [substancelab/capistrano-remote#10]
installed last released version 0.2.1

i get error:
/home/pavel/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/base.rb:506:in `handle_argument_error': ERROR: "rails_console console" was called with arguments ["production"] (Thor::InvocationError

I thing command 
rails console production just not work in new version Rails 6.
need use command
rails console -e production

Maybe you must create new release of gem???

**Comment by koppen** [comment]
You're right, I thought I had already pushed a release with that fix.

Until I get around to it, you should be able to run off the latest master, though;

    gem "capistrano-remote", :require => false, :git => "https://github.com/substancelab/capistrano-remote.git", :branch => "master"

**Comment by koppen** [comment]
And v0.3 is out containing support for Rails 6: https://rubygems.org/gems/capistrano-remote

**Comment by Grunkhead** [comment]
@nPaul use the following command 'rails console -e production'. I had the same error and this solved my env issue when opening it remotely.
